.TH "Environment.hh" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Environment.hh \- Especificación de la clase \fBEnvironment\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Expression\&.hh'\fP
.br
\fC#include 'PrimitiveOperationSpace\&.hh'\fP
.br
\fC#include 'VariableSpace\&.hh'\fP
.br
\fC#include 'OperationSpace\&.hh'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBEnvironment\fP"
.br
.RI "\fIRepresenta un entorno de ejecución con todas las operaciones primitivas predefinidas, así como con todas las variables y operaciones definidas por el usuario\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Especificación de la clase \fBEnvironment\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
