.TH "Expression.hh" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expression.hh \- Especificación de la clase \fBExpression\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBExpression\fP"
.br
.RI "\fIRepresenta una expresión, evaluable o no, mediante el resultado de evaluarla\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Especificación de la clase \fBExpression\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
