.TH "FunctionsIO.hh" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionsIO.hh \- Especificación de las operaciones de lectura/escritura de expresiones\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Environment\&.hh'\fP
.br
\fC#include 'Expression\&.hh'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBgetString\fP (string &str)"
.br
.RI "\fIOperación de separación de strings\&. \fP"
.ti -1c
.RI "bool \fBreadExpression\fP (\fBEnvironment\fP &env, \fBExpression\fP &exp)"
.br
.RI "\fIOperación de lectura de expresiones\&. \fP"
.ti -1c
.RI "void \fBwriteExpression\fP (const \fBEnvironment\fP &env, const \fBExpression\fP &exp)"
.br
.RI "\fIOperación de escritura de expresiones\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Especificación de las operaciones de lectura/escritura de expresiones\&. 


.SH "Documentación de las funciones"
.PP 
.SS "void getString (string & str)"

.PP
Operación de separación de strings\&. 
.PP
\fBPrecondición:\fP
.RS 4
\fICierto\fP 
.RE
.PP
\fBPostcondición:\fP
.RS 4
'str' es un string contenido entre espacios o paréntesis en la entrada que se ha leído 
.RE
.PP

.SS "bool readExpression (\fBEnvironment\fP & env, \fBExpression\fP & exp)"

.PP
Operación de lectura de expresiones\&. 
.PP
\fBPrecondición:\fP
.RS 4
'env' es un entorno con un espacio de operaciones primitivas inicializado con las operaciones primitivas predefinidas; 'exp' es una expresión vacía 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Se han leído los datos del canal estándar de entrada y se han asignado a 'env' si eran una definición de una variable o operación o a 'exp' si representaban una expresión evaluable 
.RE
.PP

.SS "void writeExpression (const \fBEnvironment\fP & env, const \fBExpression\fP & exp)"

.PP
Operación de escritura de expresiones\&. 
.PP
\fBPrecondición:\fP
.RS 4
'env' es un entorno con un espacio de operaciones primitivas inicializado con las operaciones primitivas predefinidas; 'exp' es una expresión no vacía 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Escribe el valor de la expresión representada por 'exp' por el canal estándar de salida 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
