.TH "main.cc" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cc \- Programa principal para la calculadora de expresiones aritméticas\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'FunctionsIO\&.hh'\fP
.br
\fC#include 'Environment\&.hh'\fP
.br
\fC#include 'Expression\&.hh'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "\fIPrograma principal para la calculadora de expresiones aritméticas\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Programa principal para la calculadora de expresiones aritméticas\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
