.TH "OperationSpace" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationSpace \- Representa un espacio de operaciones definidas por el usuario en forma de mapa de variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OperationSpace\&.hh>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBOperationSpace\fP ()"
.br
.RI "\fIConstructora por defecto\&. \fP"
.ti -1c
.RI "\fBOperationSpace\fP (string key, string parameters, string exp)"
.br
.RI "\fIConstructora con valor de inicialización\&. \fP"
.ti -1c
.RI "\fBOperationSpace\fP (const \fBOperationSpace\fP &opSpace)"
.br
.RI "\fIConstructora por copia\&. \fP"
.ti -1c
.RI "\fB~OperationSpace\fP ()"
.br
.RI "\fIDestructora por defecto\&. \fP"
.ti -1c
.RI "void \fBadd\fP (string key, string parameters, string exp)"
.br
.RI "\fIModificadora por adición de operación\&. \fP"
.ti -1c
.RI "void \fBupdate\fP (string key, string parameters, string exp)"
.br
.RI "\fIModificadora por actualización de operación\&. \fP"
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.RI "\fIConsultora de mapa vacío\&. \fP"
.ti -1c
.RI "bool \fBexists\fP (string key) const "
.br
.RI "\fIConsultora de existencia de operación\&. \fP"
.ti -1c
.RI "pair< string, string > \fBget\fP (string key)"
.br
.RI "\fIConsultora de recuperación de operación\&. \fP"
.ti -1c
.RI "int \fBnum_pars\fP (string key)"
.br
.RI "\fIConsultora de número de parámetros\&. \fP"
.ti -1c
.RI "void \fBwrite\fP () const "
.br
.RI "\fIOperación de escritura de todo el espacio de operaciones\&. \fP"
.ti -1c
.RI "void \fBwrite_op\fP (string key)"
.br
.RI "\fIOperación de escritura de una operación concreta\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Representa un espacio de operaciones definidas por el usuario en forma de mapa de variables\&. 
.SH "Documentación del constructor y destructor"
.PP 
.SS "OperationSpace::OperationSpace ()"

.PP
Constructora por defecto\&. Se ejecuta automáticamente al declarar un nuevo espacio de operaciones 
.PP
\fBPrecondición:\fP
.RS 4
\fICierto\fP 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Crea un objeto con mapa de operaciones 'opMap' vacío 
.RE
.PP

.SS "OperationSpace::OperationSpace (string key, string parameters, string exp)"

.PP
Constructora con valor de inicialización\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío; 'exp' es un string no vacío; 'key' no corresponde al nombre de ninguna de las operaciones primitivas 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Crea un objeto con mapa de operaciones 'opMap' inicializado con la operación de clave 'key', parámetros 'parameters' y expresión 'exp' 
.RE
.PP

.SS "OperationSpace::OperationSpace (const \fBOperationSpace\fP & opSpace)"

.PP
Constructora por copia\&. 
.PP
\fBPrecondición:\fP
.RS 4
\fICierto\fP 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Crea un objeto copia de 'opSpace' 
.RE
.PP

.SS "OperationSpace::~OperationSpace ()"

.PP
Destructora por defecto\&. Se ejecuta automáticamente al salir de un ámbito de visibilidad 
.PP
\fBPrecondición:\fP
.RS 4
\fICierto\fP 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Libera los recursos locales del parámetro implícito al salir de un ámbito de visibilidad 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "void OperationSpace::add (string key, string parameters, string exp)"

.PP
Modificadora por adición de operación\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío; 'key' no corresponde al nombre de ninguna de las operaciones primitivas; el mapa de operaciones 'opMap' del parámetro implícito no contiene ninguna operación con clave 'key' 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Se añade al mapa de operaciones 'opMap' del parámetro implícito la operacion con clave 'key', parámetros 'parameters' y expresión 'exp' 
.RE
.PP

.SS "bool OperationSpace::empty () const"

.PP
Consultora de mapa vacío\&. 
.PP
\fBPrecondición:\fP
.RS 4
\fICierto\fP 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Devuelve cierto si el mapa de operaciones 'opMap' está vacío 
.RE
.PP

.SS "bool OperationSpace::exists (string key) const"

.PP
Consultora de existencia de operación\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Devuelve cierto si la operación con clave 'key' existe en el mapa de operaciones 'opMap' del parámetro implícito; en otro caso, devuelve falso 
.RE
.PP

.SS "pair< string, string > OperationSpace::get (string key)"

.PP
Consultora de recuperación de operación\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío; el mapa de operaciones 'opMap' del parámetro implícito contiene una operación con clave 'key' 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Devuelve los parámetros y la expresión, respectivamente, en forma de pair, de la operación representada por la clave 'key' 
.RE
.PP

.SS "int OperationSpace::num_pars (string key)"

.PP
Consultora de número de parámetros\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío; el mapa de operaciones 'opMap' del parámetro implícito contiene una operación con clave 'key' 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Devuelve el número de parámetros de la operación representada por la clave 'key' 
.RE
.PP

.SS "void OperationSpace::update (string key, string parameters, string exp)"

.PP
Modificadora por actualización de operación\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío; 'key' no corresponde al nombre de ninguna de las operaciones primitivas; el mapa de operaciones 'opMap' del parámetro implícito contiene una operación con clave 'key' 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Los parámetros y la expresión de la operación con clave 'key' en el mapa de operaciones 'opMap' del parámetro implícito pasan a ser 'parameters' y 'exp', respectivamente 
.RE
.PP

.SS "void OperationSpace::write () const"

.PP
Operación de escritura de todo el espacio de operaciones\&. 
.PP
\fBPrecondición:\fP
.RS 4
El mapa de operaciones 'opMap' del parámetro implícito no está vacío 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Se ha escrito el contenido del mapa de operaciones 'opMap' del parámetro implícito por el canal estándar de salida 
.RE
.PP

.SS "void OperationSpace::write_op (string key)"

.PP
Operación de escritura de una operación concreta\&. 
.PP
\fBPrecondición:\fP
.RS 4
'key' es un string no vacío; el mapa de operaciones 'opMap' del parámetro implícito contiene una operación con clave 'key' 
.RE
.PP
\fBPostcondición:\fP
.RS 4
Se ha escrito el contenido de la operación con clave 'key' por el canal estándar de salida 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
