.TH "OperationSpace.hh" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationSpace.hh \- Especificación de la clase \fBOperationSpace\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBOperationSpace\fP"
.br
.RI "\fIRepresenta un espacio de operaciones definidas por el usuario en forma de mapa de variables\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Especificación de la clase \fBOperationSpace\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
