.TH "PrimitiveOperationSpace.hh" 3 "Miércoles, 7 de Diciembre de 2016" "Version v1.1" "Calculadora de expresiones aritméticas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrimitiveOperationSpace.hh \- Especificación de la clase \fBPrimitiveOperationSpace\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include 'Expression\&.hh'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPrimitiveOperationSpace\fP"
.br
.RI "\fIRepresenta un espacio de operaciones primitivas predefinidas en forma de mapa de operaciones\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Especificación de la clase \fBPrimitiveOperationSpace\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Calculadora de expresiones aritméticas del código fuente\&.
